# Generated by Django 3.2.5 on 2021-07-22 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='date_created')),
                ('updated_at', models.DateTimeField(verbose_name='date_updated')),
                ('deleted_at', models.DateTimeField(verbose_name='date_deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='date_created')),
                ('updated_at', models.DateTimeField(verbose_name='date_updated')),
                ('deleted_at', models.DateTimeField(verbose_name='date_deleted')),
                ('name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='date_created')),
                ('updated_at', models.DateTimeField(verbose_name='date_updated')),
                ('deleted_at', models.DateTimeField(verbose_name='date_deleted')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ordertype')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.stock')),
            ],
        ),
    ]
